### ISSUE TITLE
Multi-domain not working on non-standard port

### ISSUE THREAD

**Issue by catharsisjelly** [silverstripe/multi-domain#15]
So I found something that may be a small bug

I am running a site on a non-standard web port (not port 80) and found that the multi-domain module is not working. After debugging a bit your using `$_SERVER['HTTP_HOST']` which gives you the server name and the port e.g. `mysite.com:8080`

If you use `$_SERVER['SERVER_NAME']` then this give you just the `mysite.com` portion of the site, either that or in the configuration I need to define the port e.g.

```
---
Name: mymultidomain
After: '#multidomain'
---
MultiDomain:
  allow_subdomains: false
  domains:
    primary:
      hostname: 'mysite.dev'
    training:
      hostname: 'my-other-site.dev:8080'
      resolves_to: 'training'
```

I'll submit a little PR with this change but I am still testing it
